### ISSUE TITLE
Fail to convert "all_techniques" to json file

### ISSUE THREAD

**Issue by uestc-toy** [OTRF/ATTACK-Python-Client#23]
I want to convert "all_techniques" to JSON file by "json.dump" function.howerver, it reports errors "TypeError: Object of type AttackPattern is not JSON serializable"

`lift = attack_client()
all_techniques = lift.get_techniques()
all_techniques = lift.remove_revoked(all_techniques)`

**Comment by Cyb3rWard0g** [comment]
Hello @uestc-toy !

That is not an issue with the library. The output of those functions is correct. With `get_techniques()` and other functions that returns objects from ATT&CK TAXII, they are STIX objects. Therefore, you cannot simply use `json.dumps()` against the list.

You first have to serialize each STIX object in the list that you get back, then use `json.loads` to convert each object to a `dictionary` and then take the list of dictionaries and then run `json.dumos()`. Finally, you can export that to a JSON file.

This is what it would look like

![image](https://user-images.githubusercontent.com/9653181/118217703-0172ab00-b444-11eb-95db-876bc80d57a9.png)


The code I used:

```
from attackcti import attack_client
lift = attack_client()
all_techniques = lift.get_techniques()

import json
all_techniques_serialized = list(map(lambda x: json.loads(x.serialize()), all_techniques))
all_techniques_json = json.dumps(all_techniques_serialized)
```
I will close this issue since that would get you right to export the data to a json file. Feel free to re-open this issue. 

Thank you for testing our library!
