### ISSUE TITLE
Bug: enrich_data_sources is not working

### ISSUE THREAD

**Issue by Flockenmumie** [OTRF/ATTACK-Python-Client#57]
Following this manual: https://attackcti.com/playground/1-Collect_All_Functions.html#enrich-techniques-data-sources

The following lines are not working ...

```python
lift = attack_client()

def get_dataframe():
    enterprise = lift.get_techniques(enrich_data_sources=True)
    return None
```

... as the following error is generated:

```
[...]
enterprise = lift.get_techniques(enrich_data_sources=True)
  File "/home/user/.local/lib/python3.10/site-packages/attackcti/attack_api.py", line 943, in get_techniques
all_techniques = self.enrich_techniques_data_sources(all_techniques)
  File "/home/user/.local/lib/python3.10/site-packages/attackcti/attack_api.py", line 1760, in enrich_techniques_data_sources
    dc = dc_lookup[rl['source_ref']]
KeyError: 'x-mitre-data-component--4c12c1c8-bcef-4daf-8e5b-fca235f71d9e'
```

**Comment by Cyb3rWard0g** [comment]
Hello @Flockenmumie and @mihaid-b !

Sorry for the late reply. I can see ATT&CK is adding ICS data components to the framework. I do not remember that being announced as complete. I thought they were still working on it. The current version of this library only looks for Enterprise since ICS was not complete. 

I am updating the library at the moment to get it to work.

**Comment by Cyb3rWard0g** [comment]
Ok version 0.3.7 now handles ICS data components :) 

<img width="845" alt="image" src="https://user-images.githubusercontent.com/9653181/177245031-850437e1-704e-4950-8d5b-8789cdef9c49.png">

We can see the data sources and data components all together :) 

<img width="326" alt="image" src="https://user-images.githubusercontent.com/9653181/177246059-181f6cc1-fb17-4bc0-8f6b-16ac96ec6a88.png">
